### ISSUE TITLE
Pylint engine encountered an error in Codeclimate

### ISSUE THREAD

**Issue by vcalmic** [mercos/codeclimate-pylint#122] opened 2022-01-03 15:09 UTC
Hello,

The following is my pylint configuration for codeclimate:
```
---
version: "2"
checks:
  file-lines:
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 20
plugins:
  pylint:
    enabled: true
    include_paths:
      - 'foobar/'
      - 'tests/'
exclude_patterns:
  - '**/__pycache__/'
  - '**/.pytest_cache/'
```

When running Codeclimate, I received the following error: `engine produced invalid output: {:message=>"Invalid JSON", :output=>"Usage:  pylint [options] modules_or_packages\n\n  Check that module(s) satisfy a coding standard (and more !).\n\n    ` (see the attached file for more)
I tried to execute pylint locally and it worked.

[output.txt](https://github.com/mercos/codeclimate-pylint/files/7802584/output.txt)

**Comment by caiofbpa** [comment] 2022-01-04 12:29
It looks like there's a problem in the files/modules/paths selection that Codeclimate is passing to pylint.

Using both `include_paths` and `exclude_patterns` in the configuration has proven to be a source of headache for me with Codeclimate, since it's quite hard to figure out what files and paths get selected in the end. I would advise you to remove the `include_paths` clause if you can.

If you want to try to debug this further, you can run CodeClimate locally (https://github.com/codeclimate/codeclimate) using the `CODECLIMATE_DEBUG=1` and see the logs it generates, looking for the paths and files selected for analysis:

    CODECLIMATE_DEBUG=1 codeclimate analyze -e pylint

**Comment by caiofbpa** [comment] 2022-01-10 12:56
@vcalmic Did you manage to debug this? I'll close this issue in a few days as non-reproducible.

**Comment by vcalmic** [comment] 2022-01-10 14:05
@caiofbpa Thanks! I will try the steps you proposed and will let you know how it goes.

**Comment by caiofbpa** [comment] 2022-02-17 10:51
@vcalmic I'm closing this issue since it's been more than a month without an answer, so I'll assume this has been solved by the previous comments. If you still need help with this, please comment down below and I'll reopen this.

**Closed by caiofbpa** 2022-02-17 10:51 UTC
